version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:543"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

